### ISSUE TITLE
Layout Toggle?

### ISSUE THREAD

**Issue by ryanbelisle** [sonburn/symbol-organizer#1]
First off, thanks for creating this plugin! It's been a great help in making my symbols page more approachable and organized.

I have an idea if you are open to it? Provide a toggle that would allow you to switch between the current 'vertical' layout and create a new 'horizontal' layout. Horizontal layout would position the symbols from left to right first, then top to bottom.

**Comment by sonburn** [comment]
Ask and you shall receive. :)

**Comment by ryanbelisle** [comment]
Thanks @sonburn this is awesome!
