### ISSUE TITLE
Plugin doesn't work anymore on Sketch older versions

### ISSUE THREAD

**Issue by FabienLaborie** [sonburn/symbol-organizer#100]
Because of the Sketch 52 update, the plugin doesn't work on previous versions such as 51. Is there any way to make it work again?
Thanks,

**Comment by sonburn** [comment]
@FabienLaborie, @netizenwu, thank you for bringing this to my attention, apologies for the inconvenience! I was able to confirm that using Symbol Organizer with titles in versions prior to Sketch 52 was indeed broken. I just published a fix for backwards compatibility (v15.6). Please update and let me know if it resolves your issue.

**Comment by netizenwu** [comment]
I'm sincere thanks to your hotfix.
