### ISSUE TITLE
Symbol organiser doesn't work for 1 of my sketch file.

### ISSUE THREAD

**Issue by mokulawa** [sonburn/symbol-organizer#101]
Sketch 51.3
after I run the symbol organiser. It only organised the symbol order in the folder list, but the view of symbol page doesn't change. It happen only to one of my sketch file, other ones works file.

**Comment by sonburn** [comment]
@mokulawa are you using Symbol Organizer with titles by chance? There was an issue when using titles in versions prior to Sketch 52, which I just resolved (v15.6). Could you please update and let me know if it resolves your issue?

**Comment by mokulawa** [comment]
@sonburn Hi, I updated and now it works for me :D thank you very much !

**Comment by sonburn** [comment]
Great news! Thank you for using my plugin! I will close this issue now.
