### ISSUE TITLE
Can't update to 15.7

### ISSUE THREAD

**Issue by Maikenvv** [sonburn/symbol-organizer#102]
Sketch keeps mentioning to me 15.7 is available, but the update button does not work. Runner doesn't think there is a update. If I try updating by downloading a zip from GitHub it still mentions 15.6. 

I did a temporary fix for myself by editing the `manifest.json`. This doesn't fix the problem in a consistent way.

<img width="632" alt="schermafbeelding 2018-10-16 om 10 37 54" src="https://user-images.githubusercontent.com/5713166/47003552-c6932400-d12f-11e8-89ff-62114234c0fc.png">

**Comment by elitedesignsolutions** [comment]
Seems like it is the old file. It asks me if I want to replace 15.6 with 15.6.
![screen shot 2018-10-16 at 7 52 00 am](https://user-images.githubusercontent.com/18663061/47017652-7066b680-d118-11e8-946e-580fff8a6008.png)

**Comment by Drobecdao** [comment]
> Sketch keeps mentioning to me 15.7 is available, but the update button does not work. Runner doesn't think there is a update. If I try updating by downloading a zip from GitHub it still mentions 15.6.
> 
> I did a temporary fix for myself by editing the `manifest.json`. This doesn't fix the problem in a consistent way.
> 
> <img alt="schermafbeelding 2018-10-16 om 10 37 54" width="632" src="https://user-images.githubusercontent.com/5713166/47003552-c6932400-d12f-11e8-89ff-62114234c0fc.png">

Same for me :(
