### ISSUE TITLE
Group title doubling with new Sketch version 52.2

### ISSUE THREAD

**Issue by MaggiP** [sonburn/symbol-organizer#103]
![symbol organizer - group title doubled](https://user-images.githubusercontent.com/44405822/47367267-5ba49880-d6ad-11e8-850e-e1dae18c86cb.png)

**Comment by M4CC** [comment]
I'm encountering the same issue.

**Comment by MaggiP** [comment]
@sonburn, I have version 15.7. I'm using Sketch 52.3 on Mojave 10.14.1. I get a second set of labels that is about 500px below the first set of labels. Only the top folder of labels shows up in the label list. 

Thanks for looking into it!

**Comment by M4CC** [comment]
@sonburn it was a false alarm for me, I actually had a group of labels inside one of my symbols and they were spreading beyond the symbol's limits and overlaying other symbols juxtaposed to it. Sorry.

**Comment by MaggiP** [comment]
Oops, me too. Figured out the way to search for Titles folders and found a second! Feel free to close this issue.

**Comment by sonburn** [comment]
@M4CC, @MaggiP, thanks for responding... glad we were able to determine that it wasn't a bigger issue with the plugin. I have an idea for how to prevent that from happening in the future, I will add it as an enhancement in a future update. Thanks for using my plugin!!

**Comment by MaggiP** [comment]
It's a fantastic plugin and everyone I've ever worked with has used & loved it. 👍
