### ISSUE TITLE
Titles left from previous sorts

### ISSUE THREAD

**Issue by FeeoStephenson** [sonburn/symbol-organizer#108]
I'm getting titles left over from previous sorts that I cannot select or access in anyway. You can see in the attached screenshots that the current Titles are in their folder but when I hide that folder the ghost titles are still visible.
<img width="941" alt="screen shot 2019-01-10 at 9 51 38 am" src="https://user-images.githubusercontent.com/46567876/50976218-6f49e900-14bd-11e9-9ccb-148b6c82a1f6.png">
<img width="866" alt="screen shot 2019-01-10 at 9 51 24 am" src="https://user-images.githubusercontent.com/46567876/50976221-707b1600-14bd-11e9-8f00-87a7fcb4e448.png">

**Comment by sonburn** [comment]
@FeeoStephenson Is it possible there is a duplicate Titles folder somewhere in one of your symbols? This could happen if you move symbols around on your own, and it intersects with the Titles group, thus pulling it into the symbol. Try using the filter in the bottom left of Sketch, and looking for groups called "Titles"?

**Comment by FeeoStephenson** [comment]
Found it thanks a ton!

**Comment by sonburn** [comment]
@FeeoStephenson Awesome, glad you figured it out. I do have an idea on how to prevent this from happening again in the future, just need to find the time to implement it. Thanks for using my plugin!
