### ISSUE TITLE
Symbols overlap

### ISSUE THREAD

**Issue by Cielber** [sonburn/symbol-organizer#109]
Symbols overlap. It seems like the plugin has troubles reading the with of a symbol.

<img width="1385" alt="screenshot 2019-01-22 at 13 53 09" src="https://user-images.githubusercontent.com/42000917/51536814-11b68480-1e4d-11e9-830d-54dd60755d5a.png">

**Comment by Cielber** [comment]
And suddenly, after updating a text style, it was working as usual. And, I can't reproduce the bug any more. So, no need to look into this, until I can find a way to reproduce it.

**Comment by sonburn** [comment]
@Cielber Glad the issue resolved itself, not sure what happened there. Please do let me know if it happens again. Thanks for using my plugin!
