### ISSUE TITLE
More than 4 levels?

### ISSUE THREAD

**Issue by bensmeets** [sonburn/symbol-organizer#11]
Great plugin!

Is it correct, that it only supports folder levels up to 4 levels deep? If I manually add another "label/" in the granularity field, it seems to ignore it?

**Comment by sonburn** [comment]
That's correct. I have never really liked the way I have this option depicted, so I will continue to think of ways to improve it and make it more flexible.

**Comment by bensmeets** [comment]
Ok. I've been toying around with the logic how these groups are decided a bit, but more complex then I hoped :) The current implementation just looks at strings and ordering by name (as far as I could tell) and groups accordingly. But that seems to mean it glitches sometimes. Putting stuff that is in a subgroup not directly next to it's parent.

I tried figuring out a way to look at the actual tree structure of the groups and have different margins between them. E.g., if it's a subgroup, place it closer to it's parent, and more spacing between root-folders etc.. But it's harder than I thought :)

**Comment by sonburn** [comment]
The group bounds are defined by the "granularity" setting, but beyond that, you are right, there are no other considerations for group relationships. Considering the plugin is in a solid state (core functionality in place, no bugs that I am aware of), these are the types of ideas I will evaluate to continue to improve the plugin. Thank you!

**Comment by sonburn** [comment]
I would like to let you know that the latest update adds support for more than four levels. Please give it a spin!
