### ISSUE TITLE
Artboards on Abstract show as Changed after using Symbol Organizer

### ISSUE THREAD

**Issue by M4CC** [sonburn/symbol-organizer#112]
Hello,

It seems that every time I use Symbol Organizer and commit the changes to Abstract it'll show all the art boards as having been changed.

Is there any way for you to improve the behavior of the plugin so that this doesn't happen or should this be fixed on Abstract's end?

Thank you!

**Comment by sonburn** [comment]
@M4CC thank you for the feedback. Unfortunately there is not much I can do about this, because I have to move the symbols to organize them, and Abstract treats objects that have been moved on the canvas as a change. Thank you for using my plugin!

**Comment by M4CC** [comment]
Thank you for developing this awesome plugin! I will contact Abstract and try to get them to change this behavior!
