### ISSUE TITLE
Symbol artboards not collapsing

### ISSUE THREAD

**Issue by cpshanley** [sonburn/symbol-organizer#113]
After organising symbols on the Symbols page, all artboards were collapsed (which was really useful).

This is no longer the case.

THX

**Comment by sonburn** [comment]
@cpshanley I am going to guess you were using titles? I just resolved a bug introduced with Sketch 53; title group now requires fixGeometryWithOptions instead of resizeToFitChildrenWithOption. I just fixed this in 15.9. Can you confirm?

**Comment by cpshanley** [comment]
Brilliant. Works a treat. Terrific plugin. Cheers.
