### ISSUE TITLE
Plugin stopped working after last update.

### ISSUE THREAD

**Issue by ozgurgunes** [sonburn/symbol-organizer#118]
Here is the console log:

```
SyntaxError: JSON Parse error: Unexpected identifier "_Spec"
line: 466
sourceURL: /Users/ozgurgunes/Dropbox/Works/Library/Extensions/Sketch/Plugins/Symbol Organizer.sketchplugin/Contents/Sketch/script.js
column: 49
```

PS. "_Spec / " is the prefix of the Text Style I'm using for Titles.

**Comment by dlewand691** [comment]
Just found that I also have the same issue.

**Comment by davidklaw** [comment]
Same.

**Comment by sonburn** [comment]
@ozgurgunes, @dlewand691, @davidklaw thanks for the feedback, looking into it now.

**Comment by ehatle** [comment]
Got 1 warning that I had an artboard on my symbols page, removed it. No warning, but doesnt run. This was my first try since updating.

**Comment by verys-beasond** [comment]
Same. Not working at all. Uninstalling and attempting to re-install now.

**Comment by verys-beasond** [comment]
> Same. Not working at all. Uninstalling and attempting to re-install now.

Unsuccessful! Need to attempt installing early version.

**Comment by sonburn** [comment]
@dlewand691, @davidklaw, @ehatle, @verys-beasond Out of curiosity, are y'all also using Symbol Organizer with titles which contain special characters in them?

@ozgurgunes I just published 15.11 which handles existing titles with special characters better.

**Comment by sonburn** [comment]
@ozgurgunes BTW, providing the log output like you did was very very helpful, thank you.

**Comment by davidklaw** [comment]
@sonburn Nope, no titles here.

If it helps, I keep my plugins updated on a daily basis. I also use this plugin many times a week. Seems isolated to changes introduced in 15.10.

**Comment by davidklaw** [comment]
@sonburn 15.11 appears to have fixed the problem for me.

**Comment by sonburn** [comment]
@davidklaw Thanks for the feedback. In hindsight, the issue would still occur even if you aren't actively using titles, but if you used titles at _some_ point and possibly used a style name with a special character. Regardless, glad to hear it's working for you now.

**Comment by ehatle** [comment]
@sonburn: Only special char I use would be "/"
5.11 fixed it for me =) GJ!
For next time: how do I run the plugin in console?

**Comment by sonburn** [comment]
@ehatle 

1. In your Applications folder, open Utilities > Console.app
2. Expand ~/Library/Logs in the left window, and select com.bohemiancoding.sketch3 (if you use an app like CleanMyMac, this log folder might be missing and you will need to either 1) re-create it or 2) use Console's search - process:sketch library:sketch)
3. If there is Plugin Output.log file in the right window, select it and select Clear in the action menu
4. Run the plugin in Sketch, and if there was an error it will appear in the right window, in a file called Plugin Output.log

**Comment by davidklaw** [comment]
@sonburn You were on top of this man, thank you so much 🙇.
