### ISSUE TITLE
Add a special character to incrementation

### ISSUE THREAD

**Issue by rodnem** [sonburn/symbol-organizer#12]
Hi!

This is not really a problem but more like a supplication ;)

When I convert my UX to UI in a different file, it happens that I've got duplicate symbols.
I love your plugin, I use it a lot, combined with Rename Instances to find the duplicate symbols in all my artboards.

But in the layers name there's a lot of "1" or "2", so if you add special character to the sequence of duplicated symbols (for example "#") then it will be a lot easier to find the symbols using the search field in the layer panel.

Thanks

**Comment by sonburn** [comment]
Thank you for your feedback, I have made an update that adds "copy" to the duplicate symbol numbering. So now your duplicates will say "My Symbol Copy 1", "My Symbol Copy 2", etc.
