### ISSUE TITLE
Ability to organize other pages with symbols

### ISSUE THREAD

**Issue by Myrronth** [sonburn/symbol-organizer#13]
I sometimes do split my symbols page in multiple "normal" pages based on groups. Currently, the plugin seems to organize only the "master" symbols page. Would be nice to organize other pages as well.

**Comment by thealisalem** [comment]
+1

**Comment by SofieHaugeKatan** [comment]
+1

**Comment by sonburn** [comment]
Thank you for the feedback. This seems to be the most popular request, so I will tackle this improvement next!

**Comment by sonburn** [comment]
Symbol Organizer will now work on any page (which has symbols). I also added more options to group granularity and improved clarity of the setting (and thus how the plugin works). Give it a spin and let me know if it suits your needs better!

**Comment by thealisalem** [comment]
Working great! Thanks so much.
