### ISSUE TITLE
Suffix added to each symbol name after running symbol organizer

### ISSUE THREAD

**Issue by Loricac** [sonburn/symbol-organizer#140]
Hey! It seems that running symbol organizer on our library resulted in a suffix being added to every symbol in the library.

Original symbol name:  
Icons / basket  

After: 
Icons / basket DefaultSymbolsIcons @DefaultSymbols.Icons 

Could this have been caused by the symbol organizer, and if so, do you have a reverse fix? 

Thanks a lot! Great plugin btw, been using it for years!

**Comment by sonburn** [comment]
This is not really possible... Symbol Organizer doesn't augment the names of symbols unless you are "sequentially numbering duplicates", in which case a number would simply be appended at the end. Are you sure another plugin is not the culprit? Thanks for using Symbol Organizer!

**Comment by Loricac** [comment]
Thanks a lot for your quick reply Jason. Then it must have been from something else. We will keep investigating!
