### ISSUE TITLE
Doesn't seem to be working in 72

### ISSUE THREAD

**Issue by custa1200** [sonburn/symbol-organizer#147]
as per the name, just updated to 72, tried to run both via Runner and the Plugins menu item.

**Comment by stdk00** [comment]
have the same issue here :(

**Comment by jonarmtdh** [comment]
Thanks for the speedy response @sonburn !

**Comment by sonburn** [comment]
Apparently there is a known issue with Macs with Nvidia GPUs, which is what my MBP has... so I wont be able to work on a fix until the next release (which sounds like might be as early as tomorrow).

**Comment by jonarmtdh** [comment]
@sonburn If I were rich, I'd drop ship you a 2020 Intel MBP _and_ a 2021 M1 MBP.

**Comment by stdk00** [comment]
@sonburn mine is an AMD Radeon Pro 460 and the plugin still doesn't work.

**Comment by sonburn** [comment]
@stdk00 the plugin has nothing to do with the video card. I cannot use Sketch 72 because it crashes with NVidia GPUs, therefore I cant even develop and verify a fix for the plugin.

**Comment by prvg** [comment]
I 'm just a designer. However, they mentioned the usage of an unofficial class by some plug-ins. https://spectrum.chat/sketch/bug-reports/cant-find-variable-msapplicationmetadata~0b44ab46-59e5-4736-b10c-4ec6e083d949

**Comment by sonburn** [comment]
@prvg Thank you, I do know what the issue is, but I still need to validate the fix before publishing.

**Comment by rmmc** [comment]
Latest Version 72 (124316) in my intel MacBook Pro with intel graphics, does run without crashes but the plugin does not respond.

**Comment by stephanie-walter** [comment]
Hi, I just updated to Version 72.1 (124357) because sometimes Sketch updates that are small fixes automagically fix the plugin, but not this time.
FIY I am on the new  13' M1, not sure if it's linked but it might help debug.
The plugin doesn't crash for me. The config works (aka I can open the modal) also the "there is no symbol in this page" error works. It just **does nothing** when asked to re-order (same for the "gather symbols from other pages" option)
I am using butter which is a plugin to re-arrange things (layers and artboards) and this one broke with 72 too so maybe it's the "moving things around" part that has an issue?

**Comment by sonburn** [comment]
All, I just published an updated which should address the main issue in Sketch 72, which is that there was an internal change made to how you determine the Sketch version. Could everyone here please give 15.13 a spin and let me know if you have any lingering issues?

**Comment by rmmc** [comment]
Just updated Sketch to lastest Version 72.1 (124357) and, as mentioned, SO plugin to 15.13, and it worked. 
No problems detected so far. Thanks sonburn!

**Comment by stdk00** [comment]
the plugin is working great here too! thank you so much!

**Comment by sonburn** [comment]
@stephanie-walter are you experiencing any issues with the latest version? Want to be sure what you are experiencing isn't something new.

**Comment by prvg** [comment]
working properly now. Thanks a lot for the quick fix. Have a nice cup of coffee!

**Comment by sonburn** [comment]
Marking this issue as closed, thanks all.

**Comment by stephanie-walter** [comment]
> @stephanie-walter are you experiencing any issues with the latest version? Want to be sure what you are experiencing isn't something new.

ha sorry just saw this, I just updated and it's all good. Thaank youuu :)
