### ISSUE TITLE
Doesn't work on 43.1?

### ISSUE THREAD

**Issue by bensmeets** [sonburn/symbol-organizer#16]
In my case, doesn't show a UI at all.

**Comment by sonburn** [comment]
I am running 43.1 and the plugin is displaying for me. There _was_ a bug which I _just_ resolved which was preventing the symbol groups from being collapsed, but that would not have caused the problem you are experiencing.

To confirm, the plugin will not open for you, even if you open it manually from the plugins menu (just to be some other plugin is not overriding the shortcut)? Are you able to capture any error specific to the Symbol Organizer plugin in the logs?

**Comment by bensmeets** [comment]
Not sure, it goes to the symbols page, but then it doesn't show it's regular UI. I'll see if I need to update anything manually (am using Sketchpacks)

**Comment by sonburn** [comment]
I just tried the same, and the plugin takes me to the Symbols page and also loads the UI. Are you able to view logs to see if there are any clues as to the problem? If you don't know how, I can help.

Another option would be to create a brand new file, create a symbol, and try the plugin. If that works maybe there is something specific about your original file. If the original file doesn't contain sensitive information, I would be happy to take a look.

**Comment by bensmeets** [comment]
Good one, creating a new file + 1 symbol does work. So it must be something with the file (can't share it unfortunately). I'll dive deeper to check.

**Comment by bensmeets** [comment]
Figured it out! Let me explain.

- Had symbol organizer working
- Adjusted the script to be able to have some deeper levels (added "/Label/" to the "getLayoutSettings" function)
- Used it in that way (index 4 in that array)
- Updated the plugin to use Sketchpacks (without my manual tweak)
- Ran the plugin again
- It tries to use my last used settings for that specific file, which means it's trying to use an array index out of bounds.

So added that manual tweak again and it started working right away.

**Comment by sonburn** [comment]
Before you go modifying the code again, I am about to check in an update that allows for greater granularity control since it seems to be a common request. Will message here again when it's published.

**Comment by sonburn** [comment]
I have published an update which adds more granularity options for you, as well as some clarity around the setting (and thus how the plugin works). I have also made it so the plugin will work on any page with (just) symbols. Give it a spin and let me know if it suits your needs better!

**Comment by bensmeets** [comment]
Cool, works! Thanks.
