### ISSUE TITLE
Not working with the latest sketch release

### ISSUE THREAD

**Issue by JoeAllison** [sonburn/symbol-organizer#20]
When running the organiser on the latest sketch release, sketch loads continuously and isn't responding. 

Are you aware of the issue? We've become really reliant on this great plugin as part of our design process, it would be a shame not to be able to use it.

Thanks,
– Joe

**Comment by sonburn** [comment]
I just upgraded to Sketch 44  and ran the plugin through the paces and didn't run into any issue. Can you describe which settings you are using (or provide screenshot) and do the Sketch logs tell you anything (do you know how to view those)?

**Comment by JoeAllison** [comment]
Hi there,

It's occuring on both our IOS and Android app documents on 2 different machines.

The documents are very large with a few hundred artboards in total, across 38 pages. The plugin was working well up until the latest sketch release: Sketch 44 (41411)

I've attached the error log that's coming out from our Android app document.

Please let me know if you need any more information.

Thanks,
– Joe



[sketch_symbol_organiser_error.txt](https://github.com/sonburn/symbol-organizer/files/1028362/sketch_symbol_organiser_error.txt)

**Comment by PPacie** [comment]
Hi @sonburn, 

Do you have any news about this issue? It's not working either on version 45.2.

All the symbols on the symbols page are disappearing when I run the plugin.

Thanks in advance,
Pablo.

**Comment by sonburn** [comment]
@PPacie Please download the latest version of this plugin (11.4). Symbol Organizer most definitely works in 45.2.

**Comment by PPacie** [comment]
Hi @sonburn, I've deleted other plugins and reinstalled the 11.4 version. Now it's working back again 👍 

Thank you very much,
Pablo.
