### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [sonburn/symbol-organizer#21]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by sonburn** [comment]
@bomberstudios This has been done, although I am finding it difficult to prove that it has been done correctly.

Will it show there is an update only if the previously installed version had appcast included, or if latest version with appcast support is newer than any previous version?

**Comment by bomberstudios** [comment]
Only if the installed version already has an appcast field.

**Comment by bomberstudios** [comment]
You can test it by adding the appcast field to an old version of the plugin locally, and it should update to the latest version on the appcast.xml

**Comment by sonburn** [comment]
Thank you for the feedback @bomberstudios.
