### ISSUE TITLE
REQUEST - Gather Symbols on a Non Symbol Page

### ISSUE THREAD

**Issue by duncanhoge** [sonburn/symbol-organizer#22]
Any chance there is a way to gather all symbols and group them on a page besides the Symbols page? I'd love to apply the layout possibilities with this plugin to quickly create a stickersheet/component list.

**Comment by sonburn** [comment]
@duncanhoge A few versions ago I added the ability to organize symbols on a page other than the main Symbols page. This means you can now perform your request, and gather all symbols to a page other than the Symbols page. The plugin stills requires at least one symbol on the page to function. Hope this satisfies your request, and thank you for your support!

**Comment by duncanhoge** [comment]
Great! Thanks a ton!

**Comment by duncanhoge** [comment]
@sonburn I have the latest version and cannot get the functionality I describe above to work. Let me clarify and see if it is something you're interested in: It would be great if we could get the _instances_ of the Symbols gathered rather than the Symbol _artboards_. Analogous functionality would be **Insert > Symbols > ALL SYMBOLS** which doesn't currently exist.

**Comment by sonburn** [comment]
@duncanhoge I ended up resolving this with another plugin which I just published, Symbol Instance Sheet (https://github.com/sonburn/symbol-instance-sheet) - Generate a sheet of symbol instances from your current document or a library.

I hope that's the solution you are looking for!

**Comment by duncanhoge** [comment]
@sonburn that's exactly what I'm looking for. Now I can use these two plugins in conjunction. Thanks!
