### ISSUE TITLE
Feature Request: Group title should respect updated font style.

### ISSUE THREAD

**Issue by willowbrae** [sonburn/symbol-organizer#24]
It is nice you can change group title above the symbols, but after running the plugin it is reset to default one - would be great if that style was preserved.

**Comment by sonburn** [comment]
@willowbrae (and @smmandersen, @guillaumechabot, @gorkarod) I just pushed v11.5 which updated default font to SF UI Text, and will also now respect user modifications to Symbol Group Title style. Thank you for the suggestion, and your support!
