### ISSUE TITLE
All symbols removed instead of orgnized in Sketch 45

### ISSUE THREAD

**Issue by darranmorris** [sonburn/symbol-organizer#25]
Just upgraded to Sketch 45 and the plugin now removes all symbols and artboards instead of organizing them. The dialog appears fine when I run the plugin, but when I hit OK all symbols are removed from the Symbols page.

**Comment by ribrob** [comment]
I can confirm this - kills everything.

**Comment by Mulleboy** [comment]
Confimed here too. Plugin broken :(

**Comment by skskeeee** [comment]
Please repair immediately !!! :(

**Comment by illustree** [comment]
confirming the same :---/ please fix asap

**Comment by sonburn** [comment]
Thanks all, sorry for the inconvenience. Updating now, and going to dig into this.

**Comment by BraverChiang** [comment]
confirm here, please fix the issue as soon as possible. A great plugin, need it so badly.

**Comment by sonburn** [comment]
Hey all, thank you so much for the feedback and support. I was of course able to reproduce the issue, and I have just published an update which I believe resolves the issue. Please download and try for yourselves, and if you could let me know so we can confidently close the issue, that would be great.

**Comment by designkai** [comment]
I can confirm that the update is working fine for me on Sketch 45. Thank you for the great work and quick fix!

**Comment by Mulleboy** [comment]
@sonburn Thanks a lot. Your plugin is just the **best.**

**Comment by chevycamaro** [comment]
@sonburn big thumbs up to you for being so awesome.

**Comment by sonburn** [comment]
Thank you @designkai, @Mulleboy, @chevycamaro!

**Comment by nicashi** [comment]
Hi, could you please suggest where/how I would update SO to the latest. My symbols all disappeared!

**Comment by sonburn** [comment]
@nicashi Just go here - https://github.com/sonburn/symbol-organizer - click Clone or Download, then Download Zip, unpack the zip and double click Symbol Organizer.sketchplugin to install the plugin, or manually move it to your plugins folder. Alternatively, you can install from a plugin management tool like Sketchrunner (which is awesome and does a lot more than manage plugins, http://sketchrunner.com/) or Sketchpacks (https://sketchpacks.com/).

**Comment by nicashi** [comment]
Thank you Jason. Is there any way to restore the killed symbols? I mean all but two are gone!! Please help

**Comment by sonburn** [comment]
@nicashi You saved your file after this happened? I am not sure why you would have done that. Regardless, you could try using Mac's file version history and roll back to the previous version - https://support.apple.com/kb/PH18862?locale=en_US

**Comment by nicashi** [comment]
Thank you. No, I haven't saved my file after this happened. I relaunched
Sketch, in a hope that it was some rendering glitch

....................................................
Regards,
Veronica A. Shimanovskaya
+1-415-619-2856
+44 (0)20 3290 2765
https://www.linkedin.com/in/shimanovskaya
<http://uk.linkedin.com/in/shimanovskaya>
[ www.yellowparrot.com <https://yellowparrot.wixsite.com/design> ]
