### ISSUE TITLE
Lost all symbols

### ISSUE THREAD

**Issue by flogrca** [sonburn/symbol-organizer#26]
Is there any chance to retrieve all symbols?
With Sketch 45 and after running symbol-organizer 11.0.0 I lost all my symbols...

**Comment by sonburn** [comment]
You saved your file after this happened? I am not sure why you would have done that...

**Comment by sonburn** [comment]
You could try using Mac's file version history which should make previous versions of a file available - https://support.apple.com/kb/PH18862?locale=en_US

**Comment by flogrca** [comment]
Thanks for you answer. I think Skechpacks didn't update symbol-organizer... 
I will follow you link. thanks

**Comment by flogrca** [comment]
It was a very good tip! I got my symbols back. Thank you very much.

**Comment by sonburn** [comment]
So happy to hear it worked for you! Thank you for using Symbol Organizer.

**Comment by davo** [comment]
Just to confirm that on Sketch v45, Symbol Organizer deletes all the symbols.

**Comment by sonburn** [comment]
@davo This has been resolved, please make sure you are using the latest version.

**Comment by davo** [comment]
@sonburn thanks Jason! This plugin is a life saver.
