### ISSUE TITLE
Broken in Sketch 45

### ISSUE THREAD

**Issue by miguelsolorio** [sonburn/symbol-organizer#27]
When using this in Sketch 45, all symbols are deleted from Sketch and breaks the document

![2017-06-28 08_37_32](https://user-images.githubusercontent.com/1030624/27646271-0d09d970-5bdd-11e7-8f41-f86ea2218dc8.gif)

**Comment by ptolp** [comment]
Yup, just noticed the same. Luckily undo still works!

**Comment by sonburn** [comment]
@miguelsolorio, @ptolp This has been resolved (https://github.com/sonburn/symbol-organizer/issues/25), please make sure you are using the latest version.
