### ISSUE TITLE
Sketch 45 BUG: Group Titles are misaligned with Symbol Groups

### ISSUE THREAD

**Issue by chrisgriffin** [sonburn/symbol-organizer#28]
Great plugin! One of the most used plugins that I use in Sketch.

I noticed this bug after downloading the plugin from github master (I downloaded it directly from github to fixed the aforementioned symbol disappearing bug reported for Sketch 45). The symbol group titles are not aligning correctly, see screenshot:

![master](https://user-images.githubusercontent.com/390/27663094-87681cc6-5c15-11e7-96b8-39c5ea853302.png)

**Comment by sonburn** [comment]
@chrisgriffin Thank you for bringing this to my attention, I noticed this issue myself yesterday as well. Will work on a fix asap.

**Comment by sonburn** [comment]
@chrisgriffin I just published an update which should fix this issue, could you please grab the latest and let me know if it works for you?

**Comment by chrisgriffin** [comment]
Just updated and it appears to be fixed. Thanks!
