### ISSUE TITLE
Triggering Symbol-Organizer would jump to the symbols page

### ISSUE THREAD

**Issue by illustree** [sonburn/symbol-organizer#29]
Would be really convenient if the plugin would automatically jump to the symbols page from any other page opened when running

thanks in advance

**Comment by sonburn** [comment]
Thanks for the feedback @illustree, this is actually how Symbol Organizer originally functioned. It was changed as I received a lot of requests for the ability to use Symbol Organizer on more pages other than the default Symbols page, so I updated the plugin to work on whatever page you have focused. Unfortunately I do not see a way to support both flavors.

**Comment by illustree** [comment]
ah ok I see ... weird, but ok ... if the community wants that then keep this functionality

**Comment by sonburn** [comment]
At first I thought it was a little weird too, however I have found it useful myself now that I have a second symbols page I use to house artboard symbols. Thanks again for your thoughtful ideas and continued support!
