### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by andreaspixsy** [sonburn/symbol-organizer#3]
Thanks for the plugin, really helpful for creating a UI Kit.

Would it be possible to display Section Headers for the groups, or is that something that Sketch would need to implement?

**Comment by sonburn** [comment]
It's definitely possible. I already have logic in another plugin to add text above artboards, containing the artboard name (for wireframing purposes). It could easily be repurposes to add labels for symbol groups. I will take a look.

**Comment by sonburn** [comment]
@andreaspixsy, I just added this functionality. Could you download the latest and let me know what you think? I plan to clean up the code a bit before broadcasting to the masses.

**Comment by sonburn** [comment]
I found a couple bugs with regards to the new group titles functionality, when testing various scenarios. Those have been squashed in a new update.

**Comment by andreaspixsy** [comment]
Thanks, looks really great. It can get a bit messy if you have mixed content with /Label/Label _and_ /Label/Label/Label at the same time, but I guess one shouldn't do this in the first place.

When the section headers are shown, you could even cut that part from the item labels to remove redundancy and make for better readability :)

Thanks so much! 👍

**Comment by andreaspixsy** [comment]
should I close the issue or will you do it?

**Comment by sonburn** [comment]
@andreaspixsy What do you mean by messy? Do you mean labels would overlap, or are they appearing inconsistently? Was the output at least predictable or understandable? It should display consistently, even if you have a varying mix of "/" counts in your labels.

In horizontal mode, if you use a high level of granularity, it's probable the titles will overlap if you leave the spacing values at their defaults (100px). In vertical mode, there should be no issues with group titles as they are displayed vertically and are right aligned.

I have two possible solutions for horizontal mode; 1) do nothing and let this user increase the horizontal spacing value to prevent overlapping, 2) try to insert line breaks after the "/" in the group title. I will give the latter a shot today.

I will close this issue when I deliver a polished version.

**Comment by andreaspixsy** [comment]
Hmm, I can't compare to old version anymore, so I'm not sure if this is true, or if my memory is clouded:

It feels like if you set it to use `"Label/Label/"` it groups items with `Label1/Label2/Item` by "Label1/Label2" and `Label1/Item` as "Label1/Item". While the old version with the same setting grouped `Label1/Label2/Item` by "Label1/Label2" (just the same), but `Label1/Item` as "Label1".

Like if you didn't have a second-level-label, it would still group, which was nice.

Not sure if this understandable :)

**Comment by andreaspixsy** [comment]
Yes, exactly what I meant. That's great.

But now the section titles all pile up on top of the second section title.

**Comment by sonburn** [comment]
Thats what I get for not testing it on my full document, apologies. Please try the latest.

**Comment by andreaspixsy** [comment]
Been there done that 😆 

Works perfectly now! 🎆

**Comment by sonburn** [comment]
Awesome. Thanks for the suggestion! I will mark this issue as closed now, and will broadcast the feature to the masses once I solve this issue of Remove Unused Symbols not picking up overrides and some instances (which I am close to finalizing). Take care!
