### ISSUE TITLE
Problem with Sketch 45

### ISSUE THREAD

**Issue by NirBenita** [sonburn/symbol-organizer#31]
After using the plugin, all artboards disappear... Can anyone else recreate?

Mac OS 10.12.5

**Comment by sonburn** [comment]
@NirBenita Are you using the latest version of the plugin? Sketch 45 introduced a nasty bug, which has already been addressed (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by NirBenita** [comment]
![image](https://user-images.githubusercontent.com/2289769/27773674-deb6c91c-5f87-11e7-92b6-89bcb2c37179.png)

**Comment by sonburn** [comment]
11.4 is the latest, and it will not automatically update from within Sketch until you update to the latest version of the plugin which also incorporated the new Sketch plugin update mechanism. Please download the latest plugin from here - https://github.com/sonburn/symbol-organizer

**Comment by NirBenita** [comment]
Thanks so much for the help and for your work 🙌  This is a massive time saver
