### ISSUE TITLE
Sketch 45.1 removing all symbols from page.

### ISSUE THREAD

**Issue by webmastercorey** [sonburn/symbol-organizer#33]
In the most recent sketch release 45.1, symbol organizer removes all symbols from the symbols page. Symbols on pages then show errors like below.

![screenshot 2017-07-03 13 34 15](https://user-images.githubusercontent.com/1663090/27804399-555ed4b2-5ff4-11e7-9c30-25388eb75a54.png)

**Comment by sonburn** [comment]
@webmastercorey Are you using the latest version of the plugin? Sketch 45 introduced a nasty bug, which has already been addressed (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by webmastercorey** [comment]
My bad. I was trying to find if there was a previous report. Sketch said "Plugins now update automatically within Sketch". Doesn't appear to be the case.

**Comment by sonburn** [comment]
@webmastercorey I understand the confusion. The new update mechanism required a code update to the plugin, therefore will only show updates from _that_ version and beyond. If you now have the latest, you should see if/when there is an update from this point on. Thank you for your support!
