### ISSUE TITLE
Not working for Sketch V.45

### ISSUE THREAD

**Issue by ChrissN** [sonburn/symbol-organizer#34]
Many plugins have stopped working for this version and this is one of them :( are you going to update to match this version? Thanks.

**Comment by userkamil** [comment]
It would be great to use this plugin again. 🤞

**Comment by webomat** [comment]
works for me on 45.1

**Comment by sonburn** [comment]
@ChrissN, @userkamil, are you using the latest version of the plugin? Sketch 45 introduced a nasty bug, which has already been addressed (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by userkamil** [comment]
@sonburn You're very right Sir, it works now. Thank you kindly.
