### ISSUE TITLE
Symbols Disappear

### ISSUE THREAD

**Issue by LisaMackin** [sonburn/symbol-organizer#35]
I just updated to Sketch 45.1 and Craft 1.0.35. Is there a conflict with these updates maybe? When I run the Symbol Organizer my symbols disappear.

**Comment by sonburn** [comment]
@LisaMackin are you using the latest version of the plugin? Sketch 45 introduced a nasty bug, which has already been addressed (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by LisaMackin** [comment]
Thank you - I was a little late to the game! All set!
