### ISSUE TITLE
WARNING - NOT COMPATIBLE WITH SKETCH 45.1 - All Symbols GONE

### ISSUE THREAD

**Issue by LinkNYC1** [sonburn/symbol-organizer#36]
Symbol Organizer is not compatible with Sketch 45.1 - After Running the script, it erases ALL symbols, used or unused and there is no way to get them back.  All you are left with is a blank symbols page and error boxes in your document. 
![image](https://user-images.githubusercontent.com/23046183/27921825-02720c7e-6247-11e7-99d1-0c3592971c3e.png)

**Comment by sonburn** [comment]
@LinkNYC1 are you using the latest version of the plugin? Sketch 45 introduced a nasty bug, which has already been addressed (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by BeastyBoy876** [comment]
Getting the same issue. Lots of red lines. I use this plugin regularly.

**Comment by sonburn** [comment]
@BeastyBoy876 did you see my comment above? The plugin has been updated, please make sure you have the latest version.
