### ISSUE TITLE
Symbol organizers not working 

### ISSUE THREAD

**Issue by betmenka** [sonburn/symbol-organizer#37]
Hey,
just run into a weirdest bug. When i run a symbol organizer in my sketch 45.2 it deletes all the symbols in a document. 
Am I the only one experiencing this?

**Comment by KendrahSmith** [comment]
Nope, I have been having the same issue as well with the 45. I also can't use the sortme tool or several others that haven't been updated to 45 compatibility.

**Comment by josh-bbn** [comment]
Me too

**Comment by sonburn** [comment]
@betmenka, @KendrahSmith, @josh-bbn are you all using the latest version of the plugin? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25).

**Comment by josh-bbn** [comment]
@sonburn i am using sketch 45.2 and Organizer 11.0

**Comment by sonburn** [comment]
@josh-bbn Symbol Organizer is at version 11.4.

**Comment by josh-bbn** [comment]
@sonburn  i updated and now it works. thanks

**Comment by betmenka** [comment]
@sonburn updated and working as a charm. Thank you!
