### ISSUE TITLE
All Symbols Deleted When Plugin is Run

### ISSUE THREAD

**Issue by aalokt89** [sonburn/symbol-organizer#38]
Every time I run the organizer plugin, it just deletes all my symbols...I'm on Sketch 45.2

https://screencast.com/t/KkyamJUqfDR

**Comment by machinic** [comment]
Double-check to see that you have the latest version of the plugin running as well. I fixed this same  issue by manually updating the symbol organizer plugin despite Sketch Runner not indicating that my plugin was out-of-date.

**Comment by sonburn** [comment]
@aalokt89 are you all using the latest version of the plugin (11.4)? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25). I just installed 45.2 and verified Symbol Organizer still works.

**Comment by sonburn** [comment]
@machinic You are right, and I think this is where a lot of confusion is coming from... Sketch will only show you if there is an update if the new plugin code was implemented in the version you have installed. If you have 11.4 installed, you should see notifications about future updates.
