### ISSUE TITLE
Configure or Sort deleting all symbols on Symbols page - Sketch 45.2

### ISSUE THREAD

**Issue by stevebrown** [sonburn/symbol-organizer#39]
Configuring Symbol Organizer or running a Sort will remove all symbols from the Symbols page. This just started happening with 45.2.

**Comment by sonburn** [comment]
@stevebrown are you using the latest version of the plugin (11.4)? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25). I have also verified Symbol Organizer works in 45.2.

**Comment by stevebrown** [comment]
@sonburn You caught me :) I had version 11.0 installed. I had assumed that Sketch or Sketchpacks had updated to the latest version, but it hadn't. It is funny that neither Sketch or Sketchpacks flagged me that there was an update.

**Comment by sonburn** [comment]
@stevebrown No worries, the new update mechanism in Sketch is causing some confusion, as it requires the version you had installed already have specific code. You should be made aware any future updates now that you have the latest version installed. Thank you for your support!
