### ISSUE TITLE
BUG: Doesn't work with the latest version of Sketch :(

### ISSUE THREAD

**Issue by aacrouch** [sonburn/symbol-organizer#40]

**Comment by sonburn** [comment]
@aacrouch are you using the latest version of the plugin (11.4)? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25). I have also verified Symbol Organizer works in 45.2.

**Comment by ralts00** [comment]
@sonburn ,Does not work in 45.2 :(
![symbol organizer](https://user-images.githubusercontent.com/5034252/28444782-3923f7d4-6d85-11e7-9fa8-b6c766d6b974.gif)

**Comment by jayliu50** [comment]
@ralts00 I saw exactly what you saw. I was on version 11.0. Then I installed latest (by downloading directly from github, not through any plugin manager), which is 11.4. Everything worked as expected, at least on my computer.

**Comment by sonburn** [comment]
Thanks @jayliu50, you are correct... @ralts00 Symbol Organizer works properly in 45.2 if you have the latest version 11.4.
