### ISSUE TITLE
No longer compatible with Sketch 45

### ISSUE THREAD

**Issue by michaels3d** [sonburn/symbol-organizer#41]
I'm running Sketch v45.2 and anytime I run the the symbol organizer it just deletes all my symbols.

**Comment by sonburn** [comment]
@michaels3d are you using the latest version of the plugin (11.4)? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25). I have also verified Symbol Organizer works in 45.2.

**Comment by michaels3d** [comment]
Oh wow, thanks for the reply.  I had updated the plugin before I wrote that message, but it looks like for some reason it wouldn't take.  I had to completely uninstall the plugin and then reinstall it.  Now all is good.  Thanks a bunch!
