### ISSUE TITLE
This wonderful organizer is not working in Sketch 45.2

### ISSUE THREAD

**Issue by thisisfrancisco** [sonburn/symbol-organizer#42]
When I run the plugin it just turns my symbols page white and nothing happens. I have confirmed the same problem with several other designers on my team.

Any word on a fix for this? I love the plugin and used it all the time.
Thank you.

**Comment by sonburn** [comment]
@thisisfrancisco are you using the latest version of the plugin (11.4)? Sketch 45 introduced a nasty bug, which was addressed back in 45.0 (https://github.com/sonburn/symbol-organizer/issues/25). I have also verified Symbol Organizer works in 45.2.

**Comment by thisisfrancisco** [comment]
I just updated, thought I had already. Problem fixed! Thanks for the prompt response. I definitely feel a bit silly.

F
