### ISSUE TITLE
Not working with Sketch 46

### ISSUE THREAD

**Issue by billbring** [sonburn/symbol-organizer#44]
After updating to Sketch 46, this plugin just seems to remove all symbols from the page.
Was working fine with Sketch 45.

**Comment by sonburn** [comment]
@billbring What version of Symbol Organizer do you have?

**Comment by billbring** [comment]
Sorry, I was on v11. just updated to 11.5 and it does work now.

**Comment by sonburn** [comment]
@billbring No worries, thank you for using Symbol Organizer!
