### ISSUE TITLE
SF UI Text is deprecated

### ISSUE THREAD

**Issue by allisonacs** [sonburn/symbol-organizer#45]
Apple is now only distributing `SF Pro` (Text and Display). It's a name only change, but you can no longer download `SF UI`.

**Comment by sonburn** [comment]
Good to know... SF UI at least came with Sierra, but come fresh installs of High Sierra, I guess some users might be without it. I'll need to come up with a fix before then. Thanks!

**Comment by rodnem** [comment]
About this ...
It annoys me (sorry) to have this "Symbol organizer" style listed and cut my so well-organized text styles :)

I understand the need of using a default font, but why not allowing to determine* one of the already defined style ? thus we never will have again a useless only style...

A simple field (no need for a drop-down menu).
it is our job to write it correctly ...

![image](https://user-images.githubusercontent.com/6350513/30222900-dd320cf2-94c8-11e7-8f53-c60b7bdf8bff.png)

**Comment by sonburn** [comment]
@rodnem Thinking about this now (the ability to use one's own style)... one potential issue I see is that I modify the style alignment depending on how the user orients their symbols (horizontal vs vertical).

So to use your example... if you apply a style of Black, and it's left aligned, but you use Symbol Organizer in vertical-mode, then the titles will potentially overlap with the symbols unless I change the alignment. If I change the alignment to solve for that issue, then that would affect all other instances of the style which would likely not be desirable.

An option might be to not use a style at all, but then that wouldn't give user's any ability to control the appearance themselves. I could just expose a list of installed fonts and a size field, but exposing weights for selected font might be complicated.

**Comment by rodnem** [comment]
Yeap, I understand and you’re right.
Perhaps could you let us change the font (to keep existing) and also rename it.
That way we can put it in a existing folder, and clean our listing while keeping your technical style free to be modified.
What do you think ?

**Comment by sonburn** [comment]
@rodnem Can you test this latest update for me, and let me know if this achieves what you are looking for? Also solves the issue of "SF UI Text is deprecated"... display Titles will now prefer to use "SFProText-Bold" by default, and if the font doesn't exist, will fall back to "SFUIText-Bold", or "HelveticaNeue-Bold". User can still change it to whatever they like, and it will be respected.

https://www.dropbox.com/s/g0dxgcpm4hhafo1/Symbol%20Organizer%2013.1.zip?dl=0

**Comment by sonburn** [comment]
@rodnem Think I found a bug while testing it deeper myself, stand by...

**Comment by sonburn** [comment]
I've gone ahead and checked in an update to solve the original issue of "SF UI Text is deprecated" (along with another request). If you don't mind, could you open a new issue for your request changing the font name (or using a different style if I can figure it out, I have an idea about that), so I can close this issue?
