### ISSUE TITLE
merge duplicate symbols

### ISSUE THREAD

**Issue by illustree** [sonburn/symbol-organizer#46]
that is a very smart way to solve duplicate symbols ... https://github.com/oodesign/merge-duplicate-symbols probably a nice thing for inspiration

**Comment by sonburn** [comment]
@illustree Agreed, I have that one installed and have used it a few times. I could incorporate something like it into Symbol Organizer, but I would hate to detract attention from the other plugin, and the presumed hard work that went into it. If I think of a better way to achieve the same, or an enhancement that could be made, I would consider it. Thanks for the ideas. :)
