### ISSUE TITLE
Plugin no longer works - 46.1

### ISSUE THREAD

**Issue by 360spencer** [sonburn/symbol-organizer#48]
While using Sketch 46.1, Run and organize options are both non responsive.

**Comment by sonburn** [comment]
What version of Symbol Organizer are you running?

**Comment by 360spencer** [comment]
the latest from Git, and just updated to sketch 46.2 hoping that it would work and it does not.

**Comment by 360spencer** [comment]
Updated plugin again to 12.2 after updating to 46.2. ... it works. Thanks.
