### ISSUE TITLE
Labels Overlapping Symbols After Latest Update

### ISSUE THREAD

**Issue by brandonbuttars** [sonburn/symbol-organizer#49]
Symbol Organizer 12.2 with Sketch 46.2 overlaps the label onto the symbols after this latest update.  I wondered if there were some code collision with other plugins, but I deactivated all my other plugins and it still occurs.

## Here is my configuration:

**Group Definition:**                  2nd
**Display group titles:**             true
**Layout Direction:**                  Vertical
**Horizontal Space:**                 50
**Vertical Space:**                     50
**Max Per Row/Column:**          10
**Reverse layer...:**                    false
**Sequentially...:**                      false
**Gather symbols...:**                false
**Remove unused...:**                false

When I updated the configuration and hit OK, it acts like it's suppose to.  **When I 'Run Symbol Organizer', that's when the overlap happens.**  See the attached screenshot for more details.

Can anyone else confirm this is happening to them?

![Screenshot](https://cdn.sorensonspark.com/random/Symbol_Organizer_Bug.png)

**Comment by sonburn** [comment]
After configuring my Symbol Organizer exactly as you have, I get the following (which remains true after running it again and again)...

![image](https://user-images.githubusercontent.com/248364/29431880-3268d974-835f-11e7-8cb9-39b92937bb45.png)

The fact that your font face is different, and the text appears centered, implies to me that the style was modified (and Symbol Organizer now honors user modified style). Do you recall modifying the style?

**Comment by rumilazzi** [comment]
Hi, I see exactly the same issues as described by brandonbuttar. When I run the plugin, the labels overlap, and their text is center aligned, and then it becomes correct if I open and save the configuration itself.

![image](https://user-images.githubusercontent.com/5182603/29470064-eb7ceb4e-8418-11e7-823e-6926ffbc4ab5.png)

![screen shot 2017-08-18 at 1 29 28 pm](https://user-images.githubusercontent.com/5182603/29470240-959e244e-8419-11e7-8db7-ac05f664a513.png)

**Comment by brandonbuttars** [comment]
I'm still on El Capitan OS X 10.11.6.  Not sure if that makes a difference.

**Comment by sonburn** [comment]
@brandonbuttars, @rumilazzi thanks for your feedback! I dug into this deeper and found the issue, and I believe v12.4 which I just published should resolve the issue for you. Could you please check it out and let me know?

**Comment by brandonbuttars** [comment]
@sonburn v12.4 appears to have fixed the issue.  The plugin has made managing my symbols so much easier.  Thanks for putting it together and for quickly resolving the issue.

**Comment by sonburn** [comment]
Awesome, I will go ahead and close the issue. Thanks for being a supporter of Symbol Organizer! Spread the word!!

**Comment by rumilazzi** [comment]
I just confirmed v12.4 fixed the issue for me as well. Amazing response and fix speed! I also love your plugin - thanks a lot!!!

**Comment by sonburn** [comment]
@rumilazzi Thank you!
