### ISSUE TITLE
Artboard Symbols being removed

### ISSUE THREAD

**Issue by illustree** [sonburn/symbol-organizer#5]
create an artboard and select it and create a “Artboard Symbol” ... 
This creates the symbol but still keeps the artboard where it was but its name becomes purple so that it marks - it's a symbol kind of. Changes on this purple artboard will apply to the instances directly.

anyway, when I now select “remove unused” it will remove those artboards for some reason - that's not so cool because they are for sure “used” if they are lying on my stage.

please can you fix this? 
many thanks

**Comment by sonburn** [comment]
Are you sure it's removing them, and not just moving them to the Symbols page?

**Comment by illustree** [comment]
hey … thanks for looking into … here some screenshots … 





created the symbol of the artboard … THIS does NOT create atomatically a symbols page … no idea why - sketch bug?



… now I have the artboard symbol which I can modify here directly and in addition the instances (not editable on stage)





… then I wondered why I still don’t have a Symbols Page … hm … and created one symbol of the circle





after the plugin and “remuve unsused”
it really finally moves the artboard symbol also to the symbols … 




… but at the same time it removes the original Artboard on the Stage .. that is the weird component of it

**Comment by sonburn** [comment]
Unfortunately the screenshots didn't appear in your response, but what you described is what I experienced so I think I understand it. I believe the unexpected action here is the movement of any symbols that don't reside on the symbols page, _to_ the symbols page. I actually never tested that until exploring your issue, and upon reflection, it seems like a nice feature, however I think maybe it should be exposed as an option in the plugin... something like a checkbox with a label "Gather symbols from other pages". What do you think, that would solve your issue?

**Comment by sonburn** [comment]
Can you give this version a shot?

[Symbol Organizer.zip](https://github.com/sonburn/symbol-organizer/files/687908/Symbol.Organizer.zip)

**Comment by sonburn** [comment]
In my testing I have discovered a bug in the layer list ordering. Symbols that are gathered from other pages aren't considered as part of the layer list alphabetizing the first time you run the plugin. Subsequent times they will be alphabetized properly, as they now reside on the symbols page. Once I squash this bug, it should be good to go as far as I can tell.

**Comment by illustree** [comment]
now it’s cool! It keeps the “Symbol-Artboard”-artboards where they were - great! thanks

**Comment by sonburn** [comment]
Fantastic! Will close this issue.
