### ISSUE TITLE
Artboard Symbols Deleted When Removing Unused Symbols

### ISSUE THREAD

**Issue by proxemics** [sonburn/symbol-organizer#50]
When "Remove Unused Symbols" is checked and Symbol Organizer is run, it deletes artboards that have been converted into symbols on other pages. Not sure why this happens or how it handles symbol artboards, but would be great if this would not happen. Thanks!

**Comment by sonburn** [comment]
@proxemics Artboards that are converted to Symbols _are_ just symbols, and if they aren't being instanced elsewhere, then they would be candidates for deletion. If they aren't being instance elsewhere, then I would ask why they are symbols to begin with? I could restrict Remove Unused Symbols to the current page only, let me think about this...

**Comment by proxemics** [comment]
Gotcha, thanks for the reply. That's a good point on them not being instanced somewhere else. I use them for making ux maps/flows, so most tend to be used but sometimes not all are. I usually only run remove unused symbols from the symbols page in Sketch, since Sketch puts all (most?) symbols on that page and smartly does not add artboard symbols there. But I can see how my request might conflict with the main functionality of the plug-in. But would also not frown at being able to restrict removing unused symbols to the current page, and then keep using it on the Symbols page. That could be a good solve!

Either way, thanks for the work and the great plug-in! Probably my most used Sketch plug-in!

**Comment by sonburn** [comment]
@proxemics I went ahead and made a modification to Symbol Organizer, Remove Unused Symbols will now only remove symbols if they reside on the current page you are organizing (which I think makes sense). Please download 13.1 and give it a spin.

**Comment by proxemics** [comment]
This awesome! Works great! Thanks so much!

**Comment by sonburn** [comment]
Great to hear, thank you for using Symbol Organizer! I will close the issue now.
