### ISSUE TITLE
Feature Request: Artboard Organizer

### ISSUE THREAD

**Issue by pichfl** [sonburn/symbol-organizer#51]
First: Thanks for making this addon, it makes my day so much better.

Would it be possible to create a sibling addon that organizes artboards on the current page in the same fashion Symbol Organizer does with Symbols?

**Comment by sonburn** [comment]
I've got something for this in another plugin of mine, sncr-sketch-plugin (https://github.com/sonburn/sncr-sketch-plugin)... but it has _a lot_ of other stuff in it too that might not be of interest. I've toyed with the idea of breaking it out into it's own plugin for the community... just hasn't happened yet (if I do, I will let you know :)).

Be sure to check out Ale's plugin Artboard Manager and see if that works for you - https://github.com/bomberstudios/artboard-manager

Thank you for using Symbol Organizer, glad you like it!
