### ISSUE TITLE
Doesn't work on 46.2

### ISSUE THREAD

**Issue by Nevu** [sonburn/symbol-organizer#54]
Hello!

The Plugin doesn't work on Sketch 46.2 (44496) :/
When trying to organize with „label/label“ al symbols will be deleted.

BR

**Comment by sonburn** [comment]
@Nevu What version of the plugin do you have installed?

**Comment by JenFucci** [comment]
@sonburn I'm using 46.2 too and just reinstalled the plugin (version 12.4). It's not deleting them anymore but it's not running at all.

**Comment by sonburn** [comment]
@JenFucci Can you open Sketch and then Console.app (found in Utilities). In the sidebar of Console select '~/Library/Logs', then 'com.bohemiancoding.sketch3'. Run the plugin again, and if there was an error, it should appear in Plugin Output.log. If you could share with me the error, that would help in diagnosing your issue. If there is no error, can you describe or video your experience in Sketch?

**Comment by sonburn** [comment]
Closing this issue due to lack of validation or feedback.
