### ISSUE TITLE
Issue with synced symbols [sketch 47]

### ISSUE THREAD

**Issue by RaphyRaph** [sonburn/symbol-organizer#55]
When organizing symbols on a file using synced symbols, random symbols will bee added to the symbol sheet or/and symbols pulled out of the synced library into the local symbol storage.

**Comment by sonburn** [comment]
Thank you for bringing this to my attention, I just checked in a fix (12.6) to only gather local symbols in Sketch 47. Please give it a look and verify it works well for you (as it did for me).

**Comment by RaphyRaph** [comment]
Look slike it did! Thxxxxx
