### ISSUE TITLE
Request: Group symbols by nesting level before alphabetically

### ISSUE THREAD

**Issue by ixley** [sonburn/symbol-organizer#56]
First off, I love this plugin – thanks so much for your work.

As I group symbols, I've noticed that the columns can get broken in unintended ways, by parsing starting characters before nesting depth. It would be awesome if Symbol Organizer treated each nesting level as it's own group and didn't split them like this.

### Example
**This is what happens:**

| Col 1           | Col 2                             | Col 3
| ----------- | --------------------- | -------------
| nav / forms | nav / item / -              | nav / top bar 
|                    | nav/ item / selected  | nav / workflow 
|                    |                                    | nav / workflow header 

**This is what I expect (or would prefer):**

| Col 1                 | Col 2                 |
|-----------------------|-----------------------|
| nav / forms           | nav / item / -        |
| nav/ top bar          | nav / item / selected |
| nav / workflow        |                       |
| nav / workflow header |                       |

**Comment by sonburn** [comment]
I just published an update that will trim whitespace when generating groups, which should resolve the issue you are experiencing. The fix version is 12.5, please give it a whirl!

Thank you for this feedback, and your support of Symbol Organizer. :)
