### ISSUE TITLE
Custom style for the texte style of symbol organizer

### ISSUE THREAD

**Issue by rodnem** [sonburn/symbol-organizer#58]
**New issue as asked ;)**

I understand the need of using a default font, but why not allowing to determine* one of the already defined style ? thus we will never ever have a useless style...

If a dropdown is complicated, a simple field is fine :)
It is our job to write it correctly ...

![image](https://user-images.githubusercontent.com/6350513/30954532-cdb87140-a430-11e7-927b-3689648c78c0.png)

> @rodnem Thinking about this now (the ability to use one's own style)... one potential issue I see is that I modify the style alignment depending on how the user orients their symbols (horizontal vs vertical).
> 
> So to use your example... if you apply a style of Black, and it's left aligned, but you use Symbol Organizer in vertical-mode, then the titles will potentially overlap with the symbols unless I change the alignment. If I change the alignment to solve for that issue, then that would affect all other instances of the style which would likely not be desirable.
> 
> An option might be to not use a style at all, but then that wouldn't give user's any ability to control the appearance themselves. I could just expose a list of installed fonts and a size field, but exposing weights for selected font might be complicated.

Yeap, I understand and you’re right.
Perhaps could you let us change the font (to keep existing) and also rename it.
That way we can put it in a existing folder, and clean our listing while keeping your technical style free to be modified.
What do you think ?

**Comment by rodnem** [comment]
Hi Jason :)
Just giving you an easy solution…
Can you prefix the style name with the latest glyph in the Arial (safe) which is ꜡
The style name would be "꜡ Symbol Organizer" then it will always stay at the bottom of the styles list.

Here is another glyph ⁞
It's cooler and it is also very low in the character table of Arial

**Comment by ozgurgunes** [comment]
Bump!

**Comment by sonburn** [comment]
@rodnem, @ozgurgunes, I have a solution coming for this in v15 which I am finalizing. :)
