### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by itsmeonline** [sonburn/symbol-organizer#6]
Apologies for opening a ticket here. 

However, I Just wanted to say a BIG thank you for sharing this plugin. I can't tell you what a pleasure it was to re-organise my sketch symbols (mobile components) from a large project in a beautifully ordered manner.

So to state again - a BIG thank you from me (and I'm sure many others)
//Feel free to close or discard this ticket :)
Marcus

**Comment by sonburn** [comment]
Awesome, so happy to hear it, and glad it helps you as much as it does me! Thank you for the feedback!!
