### ISSUE TITLE
Plugin broken v47.1

### ISSUE THREAD

**Issue by sarahvangough** [sonburn/symbol-organizer#62]
Since I've updated Sketch, this plugin doesn't work anymore. When I run it, it deletes all of my symbols. I LOVE this plugin too! Currently running Sketch 47.1

**Comment by sonburn** [comment]
What version of Symbol Organizer are you running? There is literally no way the symbols can be removed, however there was a bug in a really old version that has long been resolved. Can you make sure you have the latest installed?

**Comment by sarahvangough** [comment]
Argh! I'd been stuck on an old version of Sketch - when I updated Sketch to the latest the plugin was "updated" but was broken. I uninstalled the plugin then reinstalled and it worked. Sorry for the rookie mistake but thank you for replying, and for this plugin, I was struggling to work without it!

**Comment by sonburn** [comment]
No worries at all @sarahvangough, I am glad Symbol Organizer is useful for you!
