### ISSUE TITLE
Feature Request: Specify a max number of groups per row/column

### ISSUE THREAD

**Issue by ragunaru** [sonburn/symbol-organizer#64]
Really love this plugin but I'm already starting to see it becoming a little useless as soon as you scale up a little in terms of the number of symbols/groups.

This is what my very modest symbol library looks like right now (this represents a very very small part of the total future library):

![image](https://user-images.githubusercontent.com/795389/34164126-a3e33158-e4d0-11e7-9bb4-04704e1bb7fc.png)

It would be great to have the ability to set the number of groups per row/column (depending on the alignment).

**Comment by sonburn** [comment]
@ragunaru I can't make out the labels, so I don't know if it would help, but have you tried adjusting the group definition? You could always just set it to 1st, and then use the max per row/column to make a simple grid.

**Comment by sonburn** [comment]
Closing the issue as the reporter has not responded.
