### ISSUE TITLE
Remove Unused Symbols removes nested symbols

### ISSUE THREAD

**Issue by stdk00** [sonburn/symbol-organizer#66]
latest update (14.3) broke this feature. all my nested symbols are seen as unused and get deleted. i'm using sketch 48.2

**Comment by sonburn** [comment]
@stdk00, thanks for bringing this to my attention. I have rolled the plugin code back to the previous version for now, while I diagnose the problem.

**Comment by stdk00** [comment]
thanks, is working goog now
