### ISSUE TITLE
Using Symbol Organizer with UX Power Tools deletes all symbols

### ISSUE THREAD

**Issue by Ryan529** [sonburn/symbol-organizer#67]
When using symbol organizer in a document where I've installed UXPT, it will delete all symbols. This is in Sketch 48.2.

nvm, it looks like updating Symbol Organizer fixed the issue, though I wonder why it wasn't able to push an update notification through Sketch Runner.

**Comment by sonburn** [comment]
How old was your version of Symbol Organizer? If it was before version 11.3, when the Appcast support  was added (the code that alerts you about plugin updates), then you would not have been notified of an update. If you are current, all should be good! Also, the modern Symbol Organizer will never delete your symbols (unless you tell it to remove unused symbols), as all the plugin does is change a symbol's x/y coordinates. Thanks for using Symbol Organizer, happy organizing!

**Comment by Ryan529** [comment]
Thanks for the response. I believe that was the issue, it was an old
version. Updating fixed it and I'm back in business.

Thanks much!

Ryan Anderson
206.547.0954

On Feb 23, 2018 8:20 AM, "Jason Burns" <notifications@github.com> wrote:

Closed #67 <https://github.com/sonburn/symbol-organizer/issues/67>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sonburn/symbol-organizer/issues/67#event-1489418830>,
or mute the thread
