### ISSUE TITLE
Working with Abstract

### ISSUE THREAD

**Issue by rgesulfo** [sonburn/symbol-organizer#68]
My team is working in Abstract and every time someone use the plugin, all the artboards are showing up as changed in the commit. Is there a way to avoid this?
Thank you for your help.

**Comment by sonburn** [comment]
@rgesulfo I am not familiar with Abstract beyond what it does, but when using Symbol Organizer, all that changes is the x/y coordinate of the symbols and the layer list order. Is Abstract so sensitive that it's picking up those changes, or is it detecting changes to the page as a whole?

**Comment by rgesulfo** [comment]
@sonburn I think Abstract is that sensitive. Here is an example of commit where I changed pretty much nothing, but because I used your plugin, I have 116 Symbols marked as changed. But it's just the position. Is there anything your plugin could do to avoid that by any chance?
![image](https://user-images.githubusercontent.com/13984657/37614152-34782de0-2b67-11e8-98ba-e4a1cfb86b8b.png)
![image](https://user-images.githubusercontent.com/13984657/37614137-2e1f65a8-2b67-11e8-8485-55a5e9687be7.png)

Thanks for your help

**Comment by icona79** [comment]
@rgesulfo I can confirm that Abstract is Artboard position sensitive. So then, yes, if you're gonna use the plugin and it would reorder your symbols, all the moved symbols will appear as edited.

**Comment by rgesulfo** [comment]
Thanks for the confirmation :)

**Comment by sonburn** [comment]
Yea guys, sorry, I’m not sure there is much I can do if Abstract is going to consider a change to canvas position as a change to the art board.

**Comment by icona79** [comment]
@sonburn your plugin is super. Don't worry, I personally can deal with this problem :)
