### ISSUE TITLE
Requires symbols and no artboard to launch even though symbols are already defined

### ISSUE THREAD

**Issue by matthieuortalda** [sonburn/symbol-organizer#69]
I get this error message when launching from the Symbols tab: "This page contains artboards and symbols. Symbol Organizer can only be used on pages with only symbols."

Sketch Version: 46.2

**Comment by sonburn** [comment]
Do you have an artboard on the symbols page?

**Comment by matthieuortalda** [comment]
Yes, those are created automatically by Sketch when using a responsive template (Forms, Typography, Notes). 

I managed to solve the problem by deleting them.

**Comment by johnnypower2016** [comment]
I get the "This page contains artboards and symbols. " error but this doesn;t make sense because all symbols are on artboards. If not, how do I find the artboard that don't have symbols. I've got hundreds of symbols - that's why I needed the plugin in the first place!!!
