### ISSUE TITLE
Not deleting symbols after 5.0 update

### ISSUE THREAD

**Issue by mmcmsp** [sonburn/symbol-organizer#71]
After last Sketch update, it's only organizing symbols, no longer shows non-used ones to delete.

**Comment by sonburn** [comment]
@mmcmsp I am unable to reproduce any issue with removing unused symbols. Could you assist in troubleshooting the issue by following these steps...

1. Open Utilities > Console.app
2. Expand ~/Library/Logs in the left window, and select com.bohemiancoding.sketch3
3. Run the plugin in Sketch, if there was an error it will appear in the right window of Console, in a file called Plugin Output.log
4. Copy/paste the output here

**Comment by mmcmsp** [comment]
Thanks for this message. After 50.2 update problem was fixed! Many many thanks!

**Comment by sonburn** [comment]
@mmcmsp Fantastic! Thanks for using my plugin!
