### ISSUE TITLE
Even after the update for Sketch 50.1, I still get the error message of 'cannot run on a page with symbols & art-boards"

### ISSUE THREAD

**Issue by dacre8iv1** [sonburn/symbol-organizer#72]
Even after the update for Sketch 50.1, I still get the error message of 'cannot run on a page with symbols & art-boards"

**Comment by sonburn** [comment]
@dacre8iv1 I am going to close this issue in fact, as it's a duplicate of this one (https://github.com/sonburn/symbol-organizer/issues/18)

**Comment by dacre8iv1** [comment]
Thanks for your response! That would be great to explore as an enhancements since I export my symbols on artboards to my developers through Zeplin.
