### ISSUE TITLE
SO only working with new document files

### ISSUE THREAD

**Issue by raptorsrevenge** [sonburn/symbol-organizer#73]
Hello, running Sketch 50.2 and SO 15.1. SO doesn't work on my older files. When I create a new Sketch file it works. If I copy and paste all my symbols into a new document it works too. It's just older documents won't run the plugin anymore. I tried installing older versions of Sketch and the plugin and I get the same result. I'm on OSX 10.13.4. 

Thanks!

**Comment by sonburn** [comment]
@raptorsrevenge Could you tell me if you are experiencing the issue still in version 15.2 which I just published?

**Comment by sonburn** [comment]
@raptorsrevenge Awesome, sorry about the trouble! Thanks for using my plugin!
