### ISSUE TITLE
don't zoom out after organising

### ISSUE THREAD

**Issue by UsernameWasAlreadyTaken** [sonburn/symbol-organizer#77]
After organizing the symbols, the canvas is automatically zoomed out to show an overview of all symbols. 

This is really absolutely never helpful. It's just annoying, because I always have to zoom back in and find the position where I duplicated some symbols with drag+Alt and wanted them to be organized.
And since I usually have many symbols, finding the previous position is quite an effort.

So PLEASE... just remove it. Organize the symbols, but do not zoom out. Thank you!

**Comment by sonburn** [comment]
@UsernameWasAlreadyTaken, thanks for the feedback. This feature was added in response to some people wondering why everything disappeared from their view (not realizing they needed to zoom out and back in to see where their symbols were moved to). So your preference isn't universal. That being said, it's something that might be useful to add as an option, so I will consider it as a possible enhancement.

**Comment by UsernameWasAlreadyTaken** [comment]
Ok, it might be helpful if you only have 10 symbols and no idea what happens when you run the plugin. 
In my current project there are >450 symbols in >160 rows... 

It's definitely useful to add as an option. Thanks a lot!

**Comment by aentan** [comment]
+1. The zooming back in navigation a huge design system library is killing me.

**Comment by ozgurgunes** [comment]
Hello i prefer to zoom back (which is not working now). Is it possible to make this an option in configuration?

**Comment by sonburn** [comment]
@UsernameWasAlreadyTaken, @aentan, @ozgurgunes you will all be happy to know that Zoom Out is an option you can disable, in version 15.8 which I just published.

**Comment by UsernameWasAlreadyTaken** [comment]
Thanks a lot! I was already happy when it was removed in one of the previous updates :D
