### ISSUE TITLE
Titles not appearing

### ISSUE THREAD

**Issue by hvargish** [sonburn/symbol-organizer#91]
I have Display Group Titles turned on, I run Symbol Organizer and the titles do not display and nothing is in alphabetical order. This seems to be the case since running the latest Sketch update.

Sketch v52

**Comment by sonburn** [comment]
@hvargish, @barto457, seems there was a last minute change in the beta that broke any plugin that uses MSSharedStyle.alloc().initWithName_firstInstance(). I've got a fix for this, but there are other changes that I don't have a fix for yet. I will publish an update as soon as I can. In the meantime, you should still be able to use Symbol Organizer, just without titles.

**Comment by sonburn** [comment]
A fix has been released for this issue, please update to 15.3. Thank you for your patience.
