### ISSUE TITLE
Running Organizer has no effect in Sketch version 52

### ISSUE THREAD

**Issue by iconmaster** [sonburn/symbol-organizer#92]
The Configure modal opens, but the Run command has no effect (nor does it trigger any error message).

STR:

- Navigate to a Symbols page containing more than one symbol and no non-symbol artboards
- Select "Run Symbol Organizer"

Expected result:

- Symbols are laid out according to the configuration settings

Actual result:

- No effect

**Comment by jausto** [comment]
Worked in beta too

**Comment by sonburn** [comment]
@iconmaster, @jausto, seems there was a last minute change in the beta that broke any plugin that uses MSSharedStyle.alloc().initWithName_firstInstance(). I've got a fix for this, but there are other changes that I don't have a fix for yet. I will publish an update as soon as I can. In the meantime, you should still be able to use Symbol Organizer, just without titles.

**Comment by iconmaster** [comment]
I can confirm that unchecking "Display group titles" allows Symbol Organizer to function in Sketch v52. Thanks @sonburn!

**Comment by sonburn** [comment]
I am going to close this as a duplicate of https://github.com/sonburn/symbol-organizer/issues/91 which was logged first. Fix coming imminently.
